<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="SHISSARI-K92MT" failures="1" tests="3" name="Default test(failed)" time="0.019" errors="0" timestamp="4 Oct 2019 10:54:05 GMT">
  <testcase classname="testpackage.Retry" name="testTwo" time="0.007">
    <skipped/>
  </testcase> <!-- testTwo -->
  <testcase classname="testpackage.Retry" name="testTwo" time="0.0">
    <skipped/>
  </testcase> <!-- testTwo -->
  <testcase classname="testpackage.Retry" name="testTwo" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at testpackage.Retry.testTwo(Retry.java:22)
	at testpackage.Runner.main(Runner.java:22)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- testTwo -->
</testsuite> <!-- Default test(failed) -->
